baseURL = 'https://chantico-300062.ci.tno.nl/'
languageCode = 'en-us'
title = 'Chantico'
theme = 'hugo-PaperMod'
contentDir = '../docs'

[params.assets]
  disableFingerprinting = false

[[menus.main]]
  name = "How to(s)"
  identifier = "howto"
  url = "/#how-tos"
  weight = 30

[[menus.main]]
  name = "API Reference"
  identifier = "api"
  pageRef = "/api/"
  weight = 40
