apiVersion: v1
kind: ConfigMap
metadata:
  name: chantico-postgres-credentials
  labels:
    app: chantico
  namespace: chantico
data:
  POSTGRES_DB: {{ .Values.postgresDb }}
  POSTGRES_USER: {{ .Values.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chantico
  name: chantico-postgres
  namespace: chantico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantico-postgres
  template:
    metadata:
      labels:
        app: chantico-postgres
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: postgres:17.6
        name: postgres
        envFrom:
        - configMapRef:
            name: chantico-postgres-credentials
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: chantico-volume-mount
          subPath: "postgres/storage"
        ports:
        - containerPort: 5432
      initContainers:
      - image: busybox
        name: postgres-initialization
        command: ["/bin/sh"]
        args:
          - -c
          - mkdir -p /tmp/chantico-volume-mount/postgres/storage;
          - until nc -z chantico-postgres 5432; do echo waiting for postgres; sleep 2; done;
        volumeMounts:
        - mountPath: /tmp/chantico-volume-mount
          name: chantico-volume-mount
      volumes:
      - name: chantico-volume-mount
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaimName }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chantico-postgres
  labels:
    app: chantico-postgres
  namespace: chantico
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: chantico-postgres
status:
  loadBalancer: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: chantico-postgres-migration
  labels:
    app: chantico
  namespace: chantico
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: goose-migrate
          image: {{ .Values.chanticoGooseImage }}
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: chantico-postgres-credentials
          command: ["/bin/sh", "-c"]
          args:
            - |
              until nc -z chantico-postgres 5432; do
                echo "Waiting for Postgres..."; sleep 2;
              done;
              echo "Running migrations...";
              goose -dir ./ postgres "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@chantico-postgres:5432/$(POSTGRES_DB)" up
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
