apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chantico
  name: chantico-prometheus
  namespace: chantico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantico-prometheus
  template:
    metadata:
      labels:
        app: chantico-prometheus
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 1000
      containers:
      - image: prom/prometheus:v3.7.3
        name: prometheus
        command: ["prometheus"]
        args: ["--config.file=/tmp/prometheus-volume/yml/prometheus.yml", "--storage.tsdb.path=/tmp/prometheus-volume/storage", "--storage.tsdb.retention.time={{ .Values.prometheusRetention }}", "--web.enable-lifecycle", "--storage.tsdb.no-lockfile"]
        volumeMounts:
        - mountPath: "/tmp/prometheus-volume"
          name: chantico-volume-mount
          subPath: "prometheus"
        ports:
        - containerPort: 9090
      initContainers:
      - image: busybox
        name: prometheus-initialization
        command: ["/bin/sh"]
        args:
          - -c
          - |
            mkdir -p /tmp/chantico-volume-mount/prometheus/config;
            mkdir -p /tmp/chantico-volume-mount/prometheus/storage;
            mkdir -p /tmp/chantico-volume-mount/prometheus/yml;
            if [ ! -f /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml ]; then
              echo 'global:' > /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
              echo '  scrape_interval: 5s' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
              echo '  evaluation_interval: 5s' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
              echo 'scrape_configs:' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
            fi
            chmod -R 1777 /tmp/chantico-volume-mount/prometheus
        volumeMounts:
        - mountPath: "/tmp/chantico-volume-mount"
          name: chantico-volume-mount
      volumes:
      - name: chantico-volume-mount
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaimName }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chantico-prometheus
  namespace: chantico
spec:
  selector:
    app: chantico-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
