apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chantico
  name: chantico-prometheus
  namespace: chantico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chantico-prometheus
  template:
    metadata:
      labels:
        app: chantico-prometheus
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: prom/prometheus
        name: prometheus
        command: ["prometheus"]
        args: ["--config.file=/prometheus.yml", "--storage.tsdb.path=/tmp/prometheus-volume", "--storage.tsdb.retention.time={{ .Values.prometheusRetention }}"]
        volumeMounts:
        - mountPath: "/prometheus.yml"
          name: chantico-volume-mount
          subPath: "prometheus/yml/prometheus.yml"
        ports:
        - containerPort: 9090
      initContainers:
      - image: busybox
        name: prometheus-initialization
        command: ["/bin/sh"]
        args:
          - -c
          - |
            mkdir -p /tmp/chantico-volume-mount/prometheus/config;
            mkdir -p /tmp/chantico-volume-mount/prometheus/storage;
            mkdir -p /tmp/chantico-volume-mount/prometheus/yml;
            touch /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
            echo 'global:' > /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
            echo '  scrape_interval: 5s' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
            echo '  evaluation_interval: 5s' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
            echo 'scrape_configs:' >> /tmp/chantico-volume-mount/prometheus/yml/prometheus.yml;
        volumeMounts:
        - mountPath: "/tmp/chantico-volume-mount"
          name: chantico-volume-mount
      volumes:
      - name: chantico-volume-mount
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaimName }}
    restartPolicy: Always
