image: golang:1.24.5-alpine3.22

stages:
  - docker
  - build
  - release

.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  stage: build
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    BUILDKIT_SOCKET_PATH: /tmp/buildkit.sock
    BUILDKIT_SOCKET: unix://${BUILDKIT_SOCKET_PATH}
  rules:
    - if: $CI_REGISTRY
    - if: $CI_REGISTRY_USER
    - if: $CI_REGISTRY_PASSWORD
    - if: $BUILD_CONTEXT
    - if: $BUILD_DOCKERFILE
    - if: $IMAGE
    - if: $TAG
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > ~/.docker/config.json
  script:
    # Start buildkitd in background with no sandboxing and explicit socket
    - buildkitd ${BUILDKITD_FLAGS} --addr ${BUILDKIT_SOCKET} &
    # Wait for buildkit socket to become available
    - |
      for i in $(seq 10); do
        [ -S ${BUILDKIT_SOCKET_PATH} ] && break
        echo "Waiting for buildkitd to start..."
        sleep 1
      done
    # Run the build
    - |
      buildctl --addr ${BUILDKIT_SOCKET} build \
        --frontend dockerfile.v0 \
        --local context=${BUILD_CONTEXT} \
        --local dockerfile=${BUILD_DOCKERFILE} \
        --output type=image,name=$IMAGE:$TAG,push=true \
        $(for secret in $SECRETS; do printf -- "--secret $secret "; done)

chantico-goose:
  extends: .buildkit
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        TAG: latest
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        TAG: $CI_COMMIT_REF_SLUG
  variables:
    BUILD_DOCKERFILE: Dockerfile.migrations
    BUILD_CONTEXT: .
    IMAGE: "$CI_REGISTRY_IMAGE/chantico-goose"
    TAG: latest
    SECRETS: |
      id=gitlab_token_user,env=CI_TOKEN_USER
      id=gitlab_token,env=CI_TOKEN

chantico-fmt:
  stage: build
  script:
    - go fmt ./...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

release:
  stage: release
  image: node:20
  script:
    - npm install
    - npx semantic-release
  needs:
    - chantico-fmt
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
