// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package chanticosqlhelper

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Measurement struct {
	ID         pgtype.UUID
	Name       string
	IsInternal bool
	Protocol   string
	DataSource string
	Query      string
}

type MeasurementValue struct {
	ID            pgtype.UUID
	MeasurementID pgtype.UUID
	Value         string
	Timestamp     pgtype.Timestamp
}
