// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package chanticosqlhelper

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeasurement = `-- name: CreateMeasurement :one
INSERT INTO measurements (
	id, name, is_internal, protocol, data_source, query
) VALUES (
	$1, $2, $3, $4, $5, $6
)
RETURNING id, name, is_internal, protocol, data_source, query, registration_time, last_measurement_time
`

type CreateMeasurementParams struct {
	ID         pgtype.UUID
	Name       string
	IsInternal bool
	Protocol   string
	DataSource string
	Query      string
}

func (q *Queries) CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, createMeasurement,
		arg.ID,
		arg.Name,
		arg.IsInternal,
		arg.Protocol,
		arg.DataSource,
		arg.Query,
	)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsInternal,
		&i.Protocol,
		&i.DataSource,
		&i.Query,
		&i.RegistrationTime,
		&i.LastMeasurementTime,
	)
	return i, err
}

const createMeasurementValue = `-- name: CreateMeasurementValue :one
INSERT INTO measurement_values (
	measurement_id, value, timestamp_start, timestamp_end
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, measurement_id, value, timestamp_start, timestamp_end
`

type CreateMeasurementValueParams struct {
	MeasurementID  pgtype.UUID
	Value          float32
	TimestampStart pgtype.Timestamp
	TimestampEnd   pgtype.Timestamp
}

func (q *Queries) CreateMeasurementValue(ctx context.Context, arg CreateMeasurementValueParams) (MeasurementValue, error) {
	row := q.db.QueryRow(ctx, createMeasurementValue,
		arg.MeasurementID,
		arg.Value,
		arg.TimestampStart,
		arg.TimestampEnd,
	)
	var i MeasurementValue
	err := row.Scan(
		&i.ID,
		&i.MeasurementID,
		&i.Value,
		&i.TimestampStart,
		&i.TimestampEnd,
	)
	return i, err
}

const deleteMeasurement = `-- name: DeleteMeasurement :exec
DELETE FROM measurements WHERE id = $1
`

func (q *Queries) DeleteMeasurement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeasurement, id)
	return err
}

const getMeasurement = `-- name: GetMeasurement :one
SELECT id, name, is_internal, protocol, data_source, query, registration_time, last_measurement_time FROM measurements WHERE id = $1
`

func (q *Queries) GetMeasurement(ctx context.Context, id pgtype.UUID) (Measurement, error) {
	row := q.db.QueryRow(ctx, getMeasurement, id)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsInternal,
		&i.Protocol,
		&i.DataSource,
		&i.Query,
		&i.RegistrationTime,
		&i.LastMeasurementTime,
	)
	return i, err
}

const listMeasurements = `-- name: ListMeasurements :many
SELECT id, name, is_internal, protocol, data_source, query, registration_time, last_measurement_time FROM measurements
ORDER BY name
`

func (q *Queries) ListMeasurements(ctx context.Context) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, listMeasurements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsInternal,
			&i.Protocol,
			&i.DataSource,
			&i.Query,
			&i.RegistrationTime,
			&i.LastMeasurementTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastMeasurementTime = `-- name: UpdateLastMeasurementTime :one
UPDATE measurements 
SET last_measurement_time = $2 
WHERE id = $1
RETURNING id, name, is_internal, protocol, data_source, query, registration_time, last_measurement_time
`

type UpdateLastMeasurementTimeParams struct {
	ID                  pgtype.UUID
	LastMeasurementTime pgtype.Timestamp
}

func (q *Queries) UpdateLastMeasurementTime(ctx context.Context, arg UpdateLastMeasurementTimeParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, updateLastMeasurementTime, arg.ID, arg.LastMeasurementTime)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsInternal,
		&i.Protocol,
		&i.DataSource,
		&i.Query,
		&i.RegistrationTime,
		&i.LastMeasurementTime,
	)
	return i, err
}
