// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package chanticosqlhelper

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeasurement = `-- name: CreateMeasurement :one
INSERT INTO measurements (
	id, name, is_internal, protocol, data_source, query
) VALUES (
	$1, $2, $3, $4, $5, $6
)
RETURNING id, name, is_internal, protocol, data_source, query
`

type CreateMeasurementParams struct {
	ID         pgtype.UUID
	Name       string
	IsInternal bool
	Protocol   string
	DataSource string
	Query      string
}

func (q *Queries) CreateMeasurement(ctx context.Context, arg CreateMeasurementParams) (Measurement, error) {
	row := q.db.QueryRow(ctx, createMeasurement,
		arg.ID,
		arg.Name,
		arg.IsInternal,
		arg.Protocol,
		arg.DataSource,
		arg.Query,
	)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsInternal,
		&i.Protocol,
		&i.DataSource,
		&i.Query,
	)
	return i, err
}

const deleteMeasurement = `-- name: DeleteMeasurement :exec
DELETE FROM measurements WHERE id = $1
`

func (q *Queries) DeleteMeasurement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeasurement, id)
	return err
}

const getMeasurement = `-- name: GetMeasurement :one
SELECT id, name, is_internal, protocol, data_source, query FROM measurements WHERE id = $1
`

func (q *Queries) GetMeasurement(ctx context.Context, id pgtype.UUID) (Measurement, error) {
	row := q.db.QueryRow(ctx, getMeasurement, id)
	var i Measurement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsInternal,
		&i.Protocol,
		&i.DataSource,
		&i.Query,
	)
	return i, err
}

const listMeasurements = `-- name: ListMeasurements :many
SELECT id, name, is_internal, protocol, data_source, query FROM measurements
ORDER BY name
`

func (q *Queries) ListMeasurements(ctx context.Context) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, listMeasurements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsInternal,
			&i.Protocol,
			&i.DataSource,
			&i.Query,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
