apiVersion: chantico.ci.tno.nl/v1alpha1
kind: PhysicalMeasurement
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: physicalmeasurement-sample
spec:
  # TODO(user): Add fields here
