---
apiVersion: chantico.ci.tno.nl/v1alpha1
kind: DataCenterResource
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: datacenterresource-pdu1
  namespace: chantico
spec:
  type: pdu
  physicalMeasurements:
    - physicalMeasurement-pdu1-out
---
apiVersion: chantico.ci.tno.nl/v1alpha1
kind: DataCenterResource
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: datacenterresource-pdu2
  namespace: chantico
spec:
  type: pdu
  physicalMeasurements:
    - physicalMeasurement-pdu2-out
---
apiVersion: chantico.ci.tno.nl/v1alpha1
kind: DataCenterResource
metadata:
  labels:
    app.kubernetes.io/name: chantico
    app.kubernetes.io/managed-by: kustomize
  name: datacenterresource-misd-gbm-01
  namespace: chantico
spec:
  type: baremetal
  parent:
    - datacenterresource-pdu1
    - datacenterresource-pdu2
