apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chantico-snmp-prometheus-volume-claim
  namespace: chantico
spec:
  storageClassName: csi-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
