apiVersion: v2
name: chantico
description: A Helm chart for Chantico - energy monitoring system
type: application
version: 0.5.3
appVersion: "v0.5.3"
annotations:
  org.opencontainers.image.source: "https://github.com/TNO-MISD/chantico"
  org.opencontainers.image.title: "Helm chart for chantico"
  org.opencontainers.image.description: |-
    A Helm chart for Chantico - energy monitoring system

    Install: `helm install chantico oci://ghcr.io/tno-misd/charts/chantico -n chantico`
  org.opencontainers.image.version: 0.5.3
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.authors: TNO
