persistentVolumeClaimName: chantico-snmp-prometheus-volume-claim
prometheusRetention: 5h
snmpExporterAddress: chantico-snmp:9116
imagePullSecretName: regcred
controller:
  include: true
  image:
    repository: "ghcr.io/tno-misd/chantico"
    tag: ""  # defaults to Chart.version
pvc:
  include: true
  storageClassName: "csi-rbd"
  storage: 3Gi
  accessModes:
    - ReadWriteOnce