apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshfs-server
  namespace: chantico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshfs-server
  template:
    metadata:
      labels:
        app: sshfs-server
    spec:
      containers:
      - name: sshfs-server
        image: rastasheep/ubuntu-sshd:18.04
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /data
          name: data-volume
        env:
        - name: SSH_USER
          value: "user"
        - name: SSH_PASSWORD
          value: "password"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: volume-test
---
apiVersion: v1
kind: Service
metadata:
  name: sshfs-service
spec:
  selector:
    app: sshfs-server
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
